bbj-vscode/src/language/bbj-module.ts, bbj-vscode/src/language/bbj-scope.ts, bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/bbj-ws-manager.ts, bbj-vscode/src/language/bbj.langium
* Better white space handling (not done in the parser but the validation)
* Completion now works mostly as expected
* Handling of the `IfStatement` and `NEXT` token has been fixed
=> Multiple grammar improvements

bbj-vscode/src/language/bbj-scope.ts, bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/src/language/bbj-ws-manager.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, examples/if-statements.bbj
Closes https://github.com/BBx-Kitchen/bbj-language-server/issues/15
Closes https://github.com/BBx-Kitchen/bbj-language-server/issues/18
Closes https://github.com/BBx-Kitchen/bbj-language-server/issues/19
=> Improve statement syntax

bbj-vscode/src/language/bbj-validator.ts
Closes https://github.com/BBx-Kitchen/bbj-language-server/issues/59
Checks whether the current statement is preceded by a label declaration. Disables the newline validation in that case.
=> Disable newline validation for label declarations

bbj-vscode/VERBs.md, bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/bbj-value-converter.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, bbj-vscode/test/validation.test.ts, examples/files.bbj
=> Add file related verbs

bbj-vscode/package-lock.json, bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, bbj-vscode/test/validation.test.ts
=> Fix SQLEXEC without arguments after closing parenthesis

bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, examples/issue163-read.bbj, examples/test.bbj
=> Fix read statement

bbj-vscode/package-lock.json, bbj-vscode/src/language/assertions.ts, bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/validations/check-classes.ts, bbj-vscode/test/classes.test.ts, examples/issue74/folder/helper.bbj, examples/issue74/folder/helper2.bbj, examples/issue74/main.bbj
I added some checks against public/protected/private class usages.
Methods are not handled yet.
Look at #74
=> Add validation for class access-levels

bbj-vscode/package-lock.json, bbj-vscode/src/language/assertions.ts, bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/src/language/validations/check-classes.ts, bbj-vscode/test/classes.test.ts, bbj-vscode/test/parser.test.ts, bbj-vscode/test/validation.test.ts, examples/issue163-read.bbj, examples/issue74/folder/helper.bbj, examples/issue74/folder/helper2.bbj, examples/issue74/main.bbj, examples/test.bbj
* #194 
* #196  
* (partially solved) #74 with #195
=> Add latest contributions

bbj-vscode/package-lock.json, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, examples/issue190-switch-case.bbj
=> Fix comments between switch cases

bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/validations/line-break-validation.ts, bbj-vscode/test/validation.test.ts
Also validate following case:
```vb
debug = 1
PRINT "Foo"; if debug then  ; REM error here  
PRINT "top_rs_row=",3 
``` 
See https://github.com/BBx-Kitchen/bbj-language-server/issues/149#issuecomment-2501204567
=> Moved line break validation to separate file

bbj-vscode/src/language/validations/line-break-validation.ts, bbj-vscode/test/validation.test.ts, examples/using-java.bbj
=> If after If single line, single line if in functions #210 #209

bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts
=> INPUT/READ verbs standalone and with trailing comma #176

bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/test/parser.test.ts
=> Enter statement with no arguments #121

bbj-vscode/package-lock.json, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, examples/issue181-release-syntax.bbj, examples/issue182-clipfromstr-syntax.bbj
=> Fix CLIPFROMSTR syntax

bbj-vscode/package-lock.json, bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, bbj-vscode/test/validation.test.ts, examples/issue224.bbj
=> Fix array access with `ALL`

bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/validation.test.ts
=> Allow asterisk as an Expression

bbj-vscode/src/language/bbj-module.ts, bbj-vscode/src/language/bbj-semantic-token-provider.ts, bbj-vscode/src/language/lib/functions.bbl, bbj-vscode/src/language/lib/functions.ts, bbj-vscode/test/parser.test.ts, examples/functions.bbl, examples/issue191-event-type.bbj, examples/issue208-and-is-also-a-function.bbj
=> AND is also a function

bbj-vscode/src/language/bbj-token-builder.ts, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/parser.test.ts, examples/issue181-release-syntax.bbj
Closes #181 
@StephanWald I have found a solution that allows all possible expressions.
=> Allow to RELEASE on expressions

.github/workflows/build.yml, bbj-vscode/src/language/bbj-validator.ts, bbj-vscode/src/language/constants.ts, bbj-vscode/test/validation.test.ts, documentation/development.md
Closes #166
@StephanWald if you find more of these forbidden identifiers for label declarations, there will be a negative list in the validator file!
=> Add negative list for label names

bbj-vscode/package-lock.json, bbj-vscode/src/language/bbj.langium, bbj-vscode/test/imports.test.ts, examples/imports/importMe.bbj, examples/imports/oldImports.bbj, examples/imports/onlyConstructor.bbj, examples/imports/onlyStaticField.bbj, examples/imports/onlyStaticMethod.bbj
I also added some tests that verify that the parser errors are gone.
But linking error (yellow) will be present at the moment.
The linking will be fixed by @dhuebner soon.
=> Remove errors for BBj full qualified names
